public with sharing class EmailSend {
    public EmailSend() {
    }
    void submitAndProcessApprovalRequest() {
        //List<Contact> cont = [SELECT Name FROM Contact WHERE Birthdate != null AND Birthdate = TODAY];
        //User user1 = [SELECT Id FROM User WHERE Alias='alias'];
        //for(Contact c: cont){
            //Approval.ProcessSubmitRequest req1 = 
                //new Approval.ProcessSubmitRequest();
            //req1.setObjectId(c.Id);
            //req1.setSubmitterId(c.Id); 
            //req1.setProcessDefinitionNameOrId('Birthday_Approval');
            //req1.setSkipEntryCriteria(true);
            //List<Id> approvers = new List<Id>{user1.Id};
            //req1.setNextApproverIds(approvers);
            //req1.setComments('comments'); 
        //}
    }
}